---
title: "Debate #4 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

debate4_data = read.csv("./data/debate_4.csv")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r polling_comparison}
debate_compare = 
  debate4_data %>% 
  select(candidate, pre_debate, post_debate) %>% 
  pivot_longer(
    pre_debate:post_debate,
    names_to = "poll", 
    values_to = "pct"
  ) %>% 
  ggplot(aes(candidate, pct, fill = poll)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Candidate Polling Before and After Debate #4",
    x = "Candidate",
    y = "Percent",
    fill = " "
    ) +
  theme(plot.title = element_text(hjust = 0.5))

ggplotly(debate_compare)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
airtime_plot = 
  ggplot(debate4_data, aes(x = words_spoken, y = pct_change, color = candidate)) + 
  geom_point(shape = 21, size = 5, stroke = 2)

ggplotly(airtime_plot)
```

### Chart C

```{r}

```

