name: "yml"
output_dir: "."
navbar:
  title: "Home"
  right:
    - text: "Data"
      href: Data.html
    - icon: fa-envelope fa-lg
      href: mailto:<sm4594@cumc.columbia.edu>
    - icon: fa-github fa-lg
      href: http://github.com/tlayouni/debate_impact.github.io/ 
output:
  html_document:
    theme: sandstone